### ISSUE TITLE
Plug-in ts type error in vite.config.ts

### ISSUE THREAD

**Issue by anncwb** [cereschen/vite-jsx#1]
Plug-in ts type error in vite.config.ts

**Comment by anncwb** [comment]
Now it can only be used like this
```ts
plugins: [
    (createJsxPlugin as any)(),
  ],

```

**Comment by anncwb** [comment]
And this needs to be changed to optional
interface IntrinsicAttributes {
      ['v-if']?: unknown;
      ['v-else-if']?: unknown;
      ['v-else']?: unknown;
      ['v-show']?: unknown;
      ['v-html']?: unknown;
      ['v-text']?: unknown;
      ['v-model']?: unknown;
    }
  }

**Comment by anncwb** [comment]
```
interface IntrinsicAttributes {
['v-if']?: unknown;
['v-else-if']?: unknown;
['v-else']?: unknown;
['v-show']?: unknown;
['v-html']?: unknown;
['v-text']?: unknown;
['v-model']?: unknown;
}
}
```

**Comment by cereschen** [comment]
Thanks  for your issue,already fixed and updated

**Comment by anncwb** [comment]
Big problem, your plug-in may cause the component to fail responsively.

**Comment by anncwb** [comment]
```
in .tsx file

setup(){
 return () => {
      const bar = unref(getBarRef);
      const { size, move } = props;
      return (
        <div
          class={['scrollbar__bar', 'is-' + bar.key]}
          onMousedown={clickTrackHandler}
          ref={elRef}
        >
          <div
            ref={thumbRef}
            class="scrollbar__thumb"
            onMousedown={clickThumbHandler}
            style={renderThumbStyle({ size, move, bar })}
          />
        </div>
      );
    };
```
Will cause the style dynamic calculation to fail

**Comment by anncwb** [comment]
```
 style={renderThumbStyle({ size, move, bar })}  Will not be responsive, remove jsx-plugin to restore
```

**Comment by anncwb** [comment]
Other attributes should be the same. I dare not use it now

**Comment by cereschen** [comment]
I'm sorry that I didn't have a careful test before, you can update and try again

**Comment by anncwb** [comment]
It’s great, but I checked this problem for a long time before I found out

**Comment by anncwb** [comment]
class={xxx}. Will not be responsive, remove jsx-plugin to restore

**Comment by cereschen** [comment]
> class={xxx}. Will not be responsive, remove jsx-plugin to restore

can you show your code?
There is nothing wrong with my test
Do you use a functional component?
